In [1]:
# Dependencies
import pandas as pd
import numpy as np
import requests
import json

In [2]:
# Google API Key
from config import gkey
lhp_pd = pd.read_csv("blue_line.csv")
lhp_pd.head()

,location,address,city,zip_code,lat,lon,category,state,info
0,Carson,218 E. Carson Bv,NaN,28203,NaN,NaN,Blue,NaN,NaN
1,Charlotte Transportation Center/Arena,303 E. Trade St,NaN,28202,NaN,NaN,Blue,NaN,NaN
2,I-485/South Blvd,9508 South Bv,NaN,28273,NaN,NaN,Blue,NaN,NaN
3,Sharon Road West,8815 Crump Rd,NaN,28134,NaN,NaN,Blue,NaN,NaN
4,Arrowood,7717 England St,NaN,28273,NaN,NaN,Blue,NaN,NaN

In [3]:
# create a params dict that will be updated with new city each iteration
params = {"key": gkey}
# Loop through the cities_pd and run a lat/long search for each city
for index, row in lhp_pd.iterrows():
    base_url = "https://maps.googleapis.com/maps/api/geocode/json"
    
    address = row['address']
    zip_code = row['zip_code']
    # update address key value
    params['address'] = f"{address},{zip_code}"
    lat_lng = requests.get(base_url, params=params)
#     print(lat_lng.url)
    lat_lng = lat_lng.json()
    lhp_pd.loc[index, "lat"] = lat_lng["results"][0]["geometry"]["location"]["lat"]
    lhp_pd.loc[index, "lon"] = lat_lng["results"][0]["geometry"]["location"]["lng"]
lhp_pd

,location,address,city,zip_code,lat,lon,category,state,info
0,Carson,218 E. Carson Bv,NaN,28203,35.218905,-80.851835,Blue,NaN,NaN
1,Charlotte Transportation Center/Arena,303 E. Trade St,NaN,28202,35.225510,-80.840870,Blue,NaN,NaN
2,I-485/South Blvd,9508 South Bv,NaN,28273,35.106879,-80.882237,Blue,NaN,NaN
3,Sharon Road West,8815 Crump Rd,NaN,28134,35.119992,-80.882237,Blue,NaN,NaN
4,Arrowood,7717 England St,NaN,28273,35.134202,-80.876641,Blue,NaN,NaN
5,Archdale,6230 South Bv,NaN,28217,35.150680,-80.876791,Blue,NaN,NaN
6,Tyvola,5703 Old Pineville Rd,NaN,28217,35.162137,-80.877838,Blue,NaN,NaN
7,Woodlawn,4756 Old Pineville Rd,NaN,28217,35.176200,-80.879288,Blue,NaN,NaN
8,Scaleybark,3750 South Bv,NaN,28209,35.192032,-80.875522,Blue,NaN,NaN
9,New Bern,129 New Bern St,NaN,28203,35.199771,-80.868959,Blue,NaN,NaN
10,East/West,1821 Camden St,NaN,28203,35.212430,-80.858862,Blue,NaN,NaN
11,Bland St,1511 Camden Rd,NaN,28203,35.215676,-80.855333,Blue,NaN,NaN
12,3rd St/Convention Center,305 E. 3rd St,NaN,28202,35.222255,-80.845430,Blue,NaN,NaN
13,7th St,260 E. 7th St,NaN,28202,35.227316,-80.838126,Blue,NaN,NaN
14,Stonewall,260 E. Stonewall St,NaN,28202,35.221287,-80.846994,Blue,NaN,NaN
15,9th Street,239 E 9th St,NaN,28202,35.229536,-80.835229,Blue,NaN,NaN
16,Parkwood,401 Parkwood Ave,NaN,28206,35.236962,-80.823927,Blue,NaN,NaN
17,25th Street,2215 N Brevard St,NaN,28206,35.241293,-80.817357,Blue,NaN,NaN
18,36th Street,400 E 36th St,NaN,28206,35.249322,-80.806048,Blue,NaN,NaN
19,Tom Hunter,6501 N Tryon St,NaN,28213,35.277708,-80.766727,Blue,NaN,NaN
20,JW Clay Blvd,9101 N Tryon St,NaN,28262,35.309976,-80.746262,Blue,NaN,NaN
21,Old Concord Rd,5600 Old Concord Rd,NaN,28213,35.262086,-80.772476,Blue,NaN,NaN
22,Sugar Creek,700 E Sugar Creek Rd,NaN,28205,35.251674,-80.791219,Blue,NaN,NaN
23,UNC Charlotte,9025 Cameron Blvd,NaN,28262,35.311731,-80.733763,Blue,NaN,NaN
24,University City Blvd,7201 N Tryon St,NaN,28262,35.286747,-80.761149,Blue,NaN,NaN
25,McCullough,8315 N Tryon St,NaN,28262,35.300709,-80.753453,Blue,NaN,NaN

In [4]:
lhp_pd.to_csv("blue_line_coords.csv")