In [1]:
import pandas as pd

In [2]:
gold = "../GroupProject2-master/gold_line.csv"
gold_line = pd.read_csv(gold)
gold_line.head()

,location,address,city,zip_code,lat,lon,category,state,info
0,LaSalle Street,NaN,NaN,NaN,35.26298,-80.85470,Gold,NaN,NaN
1,Russell Av,NaN,NaN,NaN,35.25703,-80.85558,Gold,NaN,NaN
2,Booker Avenue/Oaklawn,NaN,NaN,NaN,35.25380,-80.85597,Gold,NaN,NaN
3,French Street,NaN,NaN,NaN,35.24685,-80.85679,Gold,NaN,NaN
4,Johnson C. Smith University,NaN,NaN,NaN,35.24173,-80.85869,Gold,NaN,NaN

In [3]:
clean_df = gold_line.drop(['address', 'city', 'zip_code', 'state', 'info'], axis=1)
clean_df

                              location       lat       lon category
0                       LaSalle Street  35.26298 -80.85470     Gold
1                           Russell Av  35.25703 -80.85558     Gold
2                Booker Avenue/Oaklawn  35.25380 -80.85597     Gold
3                        French Street  35.24685 -80.85679     Gold
4          Johnson C. Smith University  35.24173 -80.85869     Gold
5                         Bruns Avenue  35.24026 -80.85843     Gold
6                   Wesley Heights Way  35.23710 -80.85866     Gold
7                      Johnson & Wales  35.23380 -80.85113     Gold
8            Charlotte Gateway Station  35.23131 -80.84773     Gold
9                          Mint Street  35.22942 -80.84566     Gold
10                        Tryon Street  35.22720 -80.84307     Gold
11                   Hawthorne and 5th  35.23285 -80.81108     Gold
12                       Veterans Park  35.21974 -80.80409     Gold
13                   Morningside Drive  35.21930 -80.79923     Gold
14                        Arnold Drive  35.21796 -80.79440     Gold
15                    Briar Creek Road  35.21695 -80.79093     Gold
16                       Eastway Drive  35.21553 -80.78065     Gold
17                      Sheridan Drive  35.21448 -80.77286     Gold
18                         Derby Acres  35.21374 -80.77026     Gold
19           Landsdale Dr/Rosehaven Dr  35.21247 -80.76433     Gold
20                   Winterfield Place  35.21082 -80.75911     Gold
21                       Eastland Mall  35.19299 -80.76105     Gold
22             Elizabeth and Hawthorne  35.21290 -80.82559     Gold
23                    Eastway Crossing  35.21591 -80.78447     Gold
24                           Barnhardt  35.22132 -80.81854     Gold
25                    Rosa Parks Place  35.27320 -80.85441     Gold
26                          Montana Dr  35.26828 -80.85400     Gold
27                           CTC/Arena  35.22545 -80.84074     Gold
28                         Davidson St  35.22290 -80.83801     Gold
29  Central Piedmont Community College  35.20272 -80.82971     Gold
30                     McDowell Street  35.22122 -80.83608     Gold
31                   Hawthorne and 8th  35.23285 -80.81108     Gold
32                           The Plaza  35.22026 -80.81080     Gold
33                           Sunnyside  35.21981 -80.81881     Gold
34                        Irwin Avenue  35.23477 -80.85246     Gold

In [4]:
clean_df.to_html('gold_df')