In [1]:
import pandas as pd

In [2]:
red = "../GroupProject2-master/red_line.csv"
red_line = pd.read_csv(red)
red_line.head()

,location,address,city,zip_code,lat,lon,category,state,info
0,Charlotte Gateway Station,"West Trade Street Charlotte, North Carolina",NaN,28202,35.23131,-80.84773,Red,NaN,1
1,Derita,"Derita Rd, Charlotte NC",NaN,28269,35.30110,-80.80568,Red,NaN,2
2,Harris,"W.T Harris Blvd, Charlotte NC",NaN,28269,35.33518,-80.82504,Red,NaN,3
3,Eastfield,"Arthur Davis Rd, Charlotte NC",NaN,28269,35.35358,-80.82208,Red,NaN,4
4,Hambright,"Hambright Rd, Huntersville NC",NaN,28078,35.37755,-80.83361,Red,NaN,5

In [3]:
clean_df = red_line.drop(['city', 'state'], axis=1)
clean_df

,location,address,zip_code,lat,lon,category,info
0,Charlotte Gateway Station,"West Trade Street Charlotte, North Carolina",28202,35.23131,-80.84773,Red,1
1,Derita,"Derita Rd, Charlotte NC",28269,35.30110,-80.80568,Red,2
2,Harris,"W.T Harris Blvd, Charlotte NC",28269,35.33518,-80.82504,Red,3
3,Eastfield,"Arthur Davis Rd, Charlotte NC",28269,35.35358,-80.82208,Red,4
4,Hambright,"Hambright Rd, Huntersville NC",28078,35.37755,-80.83361,Red,5
5,Huntersville,Huntersville North Carolina,28078,35.41094,-80.84099,Red,6
6,Sam Furr,"Sam Furr Rd, Huntersville, NC",28078,35.44984,-80.84340,Red,7
7,Cornelius,"Cornelius, NC",28031,35.48120,-80.85783,Red,8
8,Davidson,"Davidson, NC",28035,35.50061,-80.84980,Red,9
9,Mount Mourne,"Mecklenburg, Hwy, Davidson NC",28117,35.54767,-80.84895,Red,10

In [4]:
clean_df.to_html('red_df')